import { existsSync, mkdirSync } from "fs";
import { join } from "path";
import { ShapeInfo } from "../types/shapes";
import { getLibraryRoot } from "./paths";
import { updateShapeInLibrary } from "./shapeSaver";
import { runPowerShellFile, resolvePsScript } from "../infra/powershell";

/**
 * Generate a PNG preview for a shape and update its JSON entry with the preview path.
 * Windows only (uses PowerPoint COM). On other platforms, this is a no-op.
 *
 * IMPORTANT: This function REQUIRES a native PPTX to ensure colors and formatting
 * are preserved exactly as captured. Synthetic PPTX files generated by pptxgenjs
 * will use default Office theme colors, causing color mismatches.
 *
 * @returns Absolute path to the generated PNG
 * @throws Error if native PPTX is not available
 */
export async function generatePreview(shape: ShapeInfo): Promise<string | null> {
  if (process.platform !== "win32") return null;

  const libRoot = getLibraryRoot();
  const outDir = join(libRoot, "assets", shape.category);
  try {
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  } catch {
    // Best-effort: if mkdir fails, the subsequent PPTX export will surface a usable error.
  }

  const outPng = join(outDir, `${shape.id}.png`);

  // ALWAYS require native PPTX for accurate color/formatting preservation
  let srcPptx: string | null = null;
  if (shape.nativePptx) {
    srcPptx = join(libRoot, shape.nativePptx);
  }

  if (!srcPptx || !existsSync(srcPptx)) {
    // Native PPTX is required for accurate thumbnail generation
    // Using pptxgenjs would apply default Office theme colors
    throw new Error(
      "Native PPTX required for preview generation. " +
        "Recapture this shape to generate a native PPTX file with your template theme."
    );
  }

  await exportPptxToPngWindows(srcPptx, outPng);

  // Update JSON preview path (relative to assets)
  const rel = `${shape.category}/${shape.id}.png`;
  try {
    updateShapeInLibrary(shape.id, shape.category, { preview: rel });
  } catch {
    // Library write is best-effort; the PNG itself is already on disk.
  }

  return outPng;
}

async function exportPptxToPngWindows(pptxPath: string, pngPath: string): Promise<void> {
  // Phase 4: assets/ps/export-pptx-to-png.ps1 handles the COM lifecycle
  // (attach or spawn, Export, close) and emits 'OK' on success. Errors
  // bubble through the runner's message -- the legacy "PowerShell failed"
  // prefix is no longer synthesized here because the runner itself
  // produces a consistent error message that includes the exit code.
  const result = await runPowerShellFile(resolvePsScript("export-pptx-to-png"), {
    PptPath: pptxPath,
    PngPath: pngPath,
  });
  if (result.ok === false) {
    throw new Error(result.message);
  }
}
